---
title: "Animint Tests"
author: "Kevin"
date: "Thursday, March 19, 2015"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = F, 
                      message = F, 
                      warning = F, 
                      cache = F)
```

## Easy Test

This is a visualization of the ebola outbreak in Liberia.  For some reason, `geom_line` doesn't work for the first plot so I used `geom_point` instead.

```{r test-easy, results='asis'}

library(dplyr)
library(ggplot2)
library(animint)

# loading ebola data
load("data/lib_ebola.RData")            ## contains one tbl_df called lib_ebola
ani_dat <- lib_ebola %>% 
  select(Date:Location, Total_suspected_cases) %>% 
  filter(Location != "National", !is.na(Total_suspected_cases)) %>% 
  mutate(Date = as.numeric(Date)) %>%   ## have to convert date to numeric
  data.frame()                          ## have to drop tbl_df class for animint

# getting coordinates of Liberia
load("data/Liberia-coordinates.RData")  ## contains one tbl_df call coords

# plotting -------------------------------------------------

# over time
p_time <- ggplot() + 
  make_tallrect(data = ani_dat, "Date") + 
  geom_point(aes(x = Date, y = Total_suspected_cases, colour = Location), 
            data = ani_dat) + 
  scale_x_continuous(breaks = c(1.405e9, 1.41e9, 1.415e9), 
                     labels = c("July", "September", "November")) + 
  ggtitle("Ebola Cases in Liberia in 2014") + 
  ylab("Cumulative Suspected Cases")
# map
p_map <- ggplot() + 
  geom_path(aes(x = long, y = lat, group = group), 
            data = coords, alpha = I(.7), colour = "grey", size = I(.4)) + 
  geom_point(aes(x = lon, y = lat, size = Total_suspected_cases, colour = Location, 
                 showSelected = Date), 
             data = ani_dat, alpha = I(.9)) + 
  scale_size_continuous(range = c(1, 10)) + 
  ggtitle("Ebola Cases in Liberia") + 
  xlab("Longitude") + 
  ylab("Latitude")

# animint
ani_list <- list(timeLine = p_time, 
                 ebolaMap = p_map, 
                 time = list(variable = "Date", ms = 1000))
structure(ani_list, class = "animint")
```

## Medium Test

A visualization of Brownian Motion

```{r test-med}
set.seed(42)

brownian_data <- function(niter = 100, npoints = 10) {
  # niter is the number of iterations to run
  # npoints is the number of points to visualize
  dat <- data_frame(iter = factor(rep(1:niter, npoints)), 
                    point = factor(rep(1:npoints, each = niter))) %>% 
    group_by(point) %>% 
    mutate(x = cumsum(rnorm(niter)), 
           y = cumsum(rnorm(niter))) %>% 
    ungroup()
}

plot_dat <- brownian_data(niter = 10)
p <- ggplot() + 
  geom_point(aes(x = x, y = y, colour = point, showSelected = iter, 
                 label = point), data = plot_dat) + 
  geom_text(aes(x = x, y = y, colour = point, showSelected = iter, 
                label = point), data = plot_dat) + 
  ggtitle("Brownian Motion in Two Dimensions")

# to animint --------------------------------------

structure(list(plot = p, 
               time = list(variable = "iter", ms = 1000), 
               duration = list(iter = 250)), 
          class = "animint")
```

```{r test-easy2, eval=FALSE}
p_t2 <- ggplot() + geom_point(aes(x = Date, y = Total_suspected_cases, colour = Location), data = ani_dat)
structure(list(plot=p_t2), class = 'animint')
```

